### ISSUE TITLE
Scale svg to device screen

### ISSUE THREAD

**Issue by stianlaa** [holwech/drawify#30]
#### User story
As a user I want to have svg scale to the screen I'm using

#### Tasks
- [ ] - The svg should be made to scale to a desktop screen
- [ ] - The svg should be made to scale to a mobile screen
- [ ] - The svg should be made to scale to a tablet screen
